/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SmallEodClient) {
      root.SmallEodClient = {};
    }
    root.SmallEodClient.AddressData = factory(root.SmallEodClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The AddressData model module.
   * @module model/AddressData
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>AddressData</code>.
   * @alias module:model/AddressData
   * @class
   * @param city {String} 
   * @param voivodeship {String} 
   * @param street {String} 
   * @param postalCode {String} 
   * @param houseNo {String} 
   * @param email {String} 
   * @param epuap {String} 
   */
  var exports = function(city, voivodeship, street, postalCode, houseNo, email, epuap) {
    var _this = this;

    _this['city'] = city;
    _this['voivodeship'] = voivodeship;
    _this['street'] = street;
    _this['postalCode'] = postalCode;
    _this['houseNo'] = houseNo;
    _this['email'] = email;
    _this['epuap'] = epuap;
  };

  /**
   * Constructs a <code>AddressData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddressData} obj Optional instance to populate.
   * @return {module:model/AddressData} The populated <code>AddressData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('voivodeship')) {
        obj['voivodeship'] = ApiClient.convertToType(data['voivodeship'], 'String');
      }
      if (data.hasOwnProperty('flatNo')) {
        obj['flatNo'] = ApiClient.convertToType(data['flatNo'], 'String');
      }
      if (data.hasOwnProperty('street')) {
        obj['street'] = ApiClient.convertToType(data['street'], 'String');
      }
      if (data.hasOwnProperty('postalCode')) {
        obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
      }
      if (data.hasOwnProperty('houseNo')) {
        obj['houseNo'] = ApiClient.convertToType(data['houseNo'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('epuap')) {
        obj['epuap'] = ApiClient.convertToType(data['epuap'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {String} voivodeship
   */
  exports.prototype['voivodeship'] = undefined;
  /**
   * @member {String} flatNo
   */
  exports.prototype['flatNo'] = undefined;
  /**
   * @member {String} street
   */
  exports.prototype['street'] = undefined;
  /**
   * @member {String} postalCode
   */
  exports.prototype['postalCode'] = undefined;
  /**
   * @member {String} houseNo
   */
  exports.prototype['houseNo'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} epuap
   */
  exports.prototype['epuap'] = undefined;



  return exports;
}));


