/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AdministrativeUnit model module.
 * @module model/AdministrativeUnit
 * @version 1.0.4
 */
class AdministrativeUnit {
    /**
     * Constructs a new <code>AdministrativeUnit</code>.
     * AdministrativeUnit(id, parent, name, category, slug, updated_on, active, lft, rght, tree_id, level)
     * @alias module:model/AdministrativeUnit
     * @param id {String} 
     * @param name {String} 
     * @param category {Number} 
     * @param updatedOn {Date} 
     */
    constructor(id, name, category, updatedOn) { 
        
        AdministrativeUnit.initialize(this, id, name, category, updatedOn);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, category, updatedOn) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['category'] = category;
        obj['updatedOn'] = updatedOn;
    }

    /**
     * Constructs a <code>AdministrativeUnit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AdministrativeUnit} obj Optional instance to populate.
     * @return {module:model/AdministrativeUnit} The populated <code>AdministrativeUnit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdministrativeUnit();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'Number');
            }
            if (data.hasOwnProperty('updatedOn')) {
                obj['updatedOn'] = ApiClient.convertToType(data['updatedOn'], 'Date');
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = ApiClient.convertToType(data['parent'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
AdministrativeUnit.prototype['id'] = undefined;

/**
 * @member {String} name
 */
AdministrativeUnit.prototype['name'] = undefined;

/**
 * @member {Number} category
 */
AdministrativeUnit.prototype['category'] = undefined;

/**
 * @member {Date} updatedOn
 */
AdministrativeUnit.prototype['updatedOn'] = undefined;

/**
 * @member {String} parent
 */
AdministrativeUnit.prototype['parent'] = undefined;

/**
 * @member {String} slug
 */
AdministrativeUnit.prototype['slug'] = undefined;

/**
 * @member {Boolean} active
 */
AdministrativeUnit.prototype['active'] = undefined;






export default AdministrativeUnit;

