/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DictionaryValue'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DictionaryValue'));
  } else {
    // Browser globals (root is window)
    if (!root.SmallEod) {
      root.SmallEod = {};
    }
    root.SmallEod.Dictionary = factory(root.SmallEod.ApiClient, root.SmallEod.DictionaryValue);
  }
}(this, function(ApiClient, DictionaryValue) {
  'use strict';



  /**
   * The Dictionary model module.
   * @module model/Dictionary
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Dictionary</code>.
   * A collection of dictionary data for categorizing and collecting statistical information
   * @alias module:model/Dictionary
   * @class
   * @param id {String} 
   * @param name {String} Name of the statistical field
   * @param createdOn {String} 
   * @param createdBy {String} User ID responsible for creating the content
   * @param modifiedOn {String} 
   * @param modifiedBy {String} 
   */
  var exports = function(id, name, createdOn, createdBy, modifiedOn, modifiedBy) {
    var _this = this;

    _this['id'] = id;
    _this['name'] = name;
    _this['createdOn'] = createdOn;
    _this['createdBy'] = createdBy;
    _this['modifiedOn'] = modifiedOn;
    _this['modifiedBy'] = modifiedBy;
  };

  /**
   * Constructs a <code>Dictionary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Dictionary} obj Optional instance to populate.
   * @return {module:model/Dictionary} The populated <code>Dictionary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], [DictionaryValue]);
      }
      if (data.hasOwnProperty('maxItems')) {
        obj['maxItems'] = ApiClient.convertToType(data['maxItems'], 'Number');
      }
      if (data.hasOwnProperty('minItems')) {
        obj['minItems'] = ApiClient.convertToType(data['minItems'], 'Number');
      }
      if (data.hasOwnProperty('active')) {
        obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
      }
      if (data.hasOwnProperty('createdOn')) {
        obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'String');
      }
      if (data.hasOwnProperty('createdBy')) {
        obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
      }
      if (data.hasOwnProperty('modifiedOn')) {
        obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'String');
      }
      if (data.hasOwnProperty('modifiedBy')) {
        obj['modifiedBy'] = ApiClient.convertToType(data['modifiedBy'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Name of the statistical field
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Acceptable values
   * @member {Array.<module:model/DictionaryValue>} value
   */
  exports.prototype['value'] = undefined;
  /**
   * Maximum number of selected values
   * @member {Number} maxItems
   * @default 1
   */
  exports.prototype['maxItems'] = 1;
  /**
   * Minimum number of selected values
   * @member {Number} minItems
   * @default 1
   */
  exports.prototype['minItems'] = 1;
  /**
   * Allows to add to new entries
   * @member {Boolean} active
   * @default true
   */
  exports.prototype['active'] = true;
  /**
   * @member {String} createdOn
   */
  exports.prototype['createdOn'] = undefined;
  /**
   * User ID responsible for creating the content
   * @member {String} createdBy
   */
  exports.prototype['createdBy'] = undefined;
  /**
   * @member {String} modifiedOn
   */
  exports.prototype['modifiedOn'] = undefined;
  /**
   * @member {String} modifiedBy
   */
  exports.prototype['modifiedBy'] = undefined;



  return exports;
}));


