/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The File model module.
 * @module model/File
 * @version 1.0.4
 */
class File {
    /**
     * Constructs a new <code>File</code>.
     * File(id, path, name, letter)
     * @alias module:model/File
     * @param path {String} Path to file.
     * @param name {String} Name of file.
     */
    constructor(path, name) { 
        
        File.initialize(this, path, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, path, name) { 
        obj['path'] = path;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>File</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/File} obj Optional instance to populate.
     * @return {module:model/File} The populated <code>File</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new File();

            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('downloadUrl')) {
                obj['downloadUrl'] = ApiClient.convertToType(data['downloadUrl'], 'String');
            }
            if (data.hasOwnProperty('letter')) {
                obj['letter'] = ApiClient.convertToType(data['letter'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Path to file.
 * @member {String} path
 */
File.prototype['path'] = undefined;

/**
 * Name of file.
 * @member {String} name
 */
File.prototype['name'] = undefined;

/**
 * @member {Number} id
 */
File.prototype['id'] = undefined;

/**
 * @member {String} downloadUrl
 */
File.prototype['downloadUrl'] = undefined;

/**
 * @member {Number} letter
 */
File.prototype['letter'] = undefined;






export default File;

