/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SmallEod) {
      root.SmallEod = {};
    }
    root.SmallEod.InstitutionExternalIdentifier = factory(root.SmallEod.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The InstitutionExternalIdentifier model module.
   * @module model/InstitutionExternalIdentifier
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InstitutionExternalIdentifier</code>.
   * Known external identifier of the institution
   * @alias module:model/InstitutionExternalIdentifier
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>InstitutionExternalIdentifier</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InstitutionExternalIdentifier} obj Optional instance to populate.
   * @return {module:model/InstitutionExternalIdentifier} The populated <code>InstitutionExternalIdentifier</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('regon')) {
        obj['regon'] = ApiClient.convertToType(data['regon'], 'String');
      }
      if (data.hasOwnProperty('nip')) {
        obj['nip'] = ApiClient.convertToType(data['nip'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} regon
   */
  exports.prototype['regon'] = undefined;
  /**
   * @member {String} nip
   */
  exports.prototype['nip'] = undefined;



  return exports;
}));


