/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SmallEodClient) {
      root.SmallEodClient = {};
    }
    root.SmallEodClient.ModelCase = factory(root.SmallEodClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ModelCase model module.
   * @module model/ModelCase
   * @version 1.0.4
   */

  /**
   * Constructs a new <code>ModelCase</code>.
   * @alias module:model/ModelCase
   * @class
   * @param comment {String} Comment for this case.
   * @param name {String} Case's name.
   * @param feature {Array.<Number>} 
   * @param tag {Array.<String>} 
   */
  var exports = function(comment, name, feature, tag) {
    var _this = this;

    _this['comment'] = comment;
    _this['name'] = name;
    _this['feature'] = feature;
    _this['tag'] = tag;
  };

  /**
   * Constructs a <code>ModelCase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelCase} obj Optional instance to populate.
   * @return {module:model/ModelCase} The populated <code>ModelCase</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('comment')) {
        obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('feature')) {
        obj['feature'] = ApiClient.convertToType(data['feature'], ['Number']);
      }
      if (data.hasOwnProperty('tag')) {
        obj['tag'] = ApiClient.convertToType(data['tag'], ['String']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('auditedInstitution')) {
        obj['auditedInstitution'] = ApiClient.convertToType(data['auditedInstitution'], ['Number']);
      }
      if (data.hasOwnProperty('responsibleUser')) {
        obj['responsibleUser'] = ApiClient.convertToType(data['responsibleUser'], ['Number']);
      }
      if (data.hasOwnProperty('notifiedUser')) {
        obj['notifiedUser'] = ApiClient.convertToType(data['notifiedUser'], ['Number']);
      }
      if (data.hasOwnProperty('createdBy')) {
        obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'Number');
      }
      if (data.hasOwnProperty('modifiedBy')) {
        obj['modifiedBy'] = ApiClient.convertToType(data['modifiedBy'], 'Number');
      }
      if (data.hasOwnProperty('createdOn')) {
        obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
      }
      if (data.hasOwnProperty('modifiedOn')) {
        obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'Date');
      }
    }
    return obj;
  }

  /**
   * Comment for this case.
   * @member {String} comment
   */
  exports.prototype['comment'] = undefined;
  /**
   * Case's name.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Array.<Number>} feature
   */
  exports.prototype['feature'] = undefined;
  /**
   * @member {Array.<String>} tag
   */
  exports.prototype['tag'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Case audits this Institution.
   * @member {Array.<Number>} auditedInstitution
   */
  exports.prototype['auditedInstitution'] = undefined;
  /**
   * @member {Array.<Number>} responsibleUser
   */
  exports.prototype['responsibleUser'] = undefined;
  /**
   * @member {Array.<Number>} notifiedUser
   */
  exports.prototype['notifiedUser'] = undefined;
  /**
   * @member {Number} createdBy
   */
  exports.prototype['createdBy'] = undefined;
  /**
   * @member {Number} modifiedBy
   */
  exports.prototype['modifiedBy'] = undefined;
  /**
   * @member {Date} createdOn
   */
  exports.prototype['createdOn'] = undefined;
  /**
   * @member {Date} modifiedOn
   */
  exports.prototype['modifiedOn'] = undefined;



  return exports;
}));


