/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Note model module.
 * @module model/Note
 * @version 1.0.4
 */
class Note {
    /**
     * Constructs a new <code>Note</code>.
     * Note(id, modified_on, created_on, created_by, modified_by, comment, case)
     * @alias module:model/Note
     * @param _case {Number} Related case.
     * @param comment {String} 
     */
    constructor(_case, comment) { 
        
        Note.initialize(this, _case, comment);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _case, comment) { 
        obj['case'] = _case;
        obj['comment'] = comment;
    }

    /**
     * Constructs a <code>Note</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Note} obj Optional instance to populate.
     * @return {module:model/Note} The populated <code>Note</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Note();

            if (data.hasOwnProperty('case')) {
                obj['case'] = ApiClient.convertToType(data['case'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Related case.
 * @member {Number} case
 */
Note.prototype['case'] = undefined;

/**
 * @member {String} comment
 */
Note.prototype['comment'] = undefined;

/**
 * @member {Number} id
 */
Note.prototype['id'] = undefined;






export default Note;

