/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RefreshTokenRequest model module.
 * @module model/RefreshTokenRequest
 * @version 1.0.4
 */
class RefreshTokenRequest {
    /**
     * Constructs a new <code>RefreshTokenRequest</code>.
     * @alias module:model/RefreshTokenRequest
     * @param refreshToken {String} 
     */
    constructor(refreshToken) { 
        
        RefreshTokenRequest.initialize(this, refreshToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, refreshToken) { 
        obj['refreshToken'] = refreshToken;
    }

    /**
     * Constructs a <code>RefreshTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RefreshTokenRequest} obj Optional instance to populate.
     * @return {module:model/RefreshTokenRequest} The populated <code>RefreshTokenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RefreshTokenRequest();

            if (data.hasOwnProperty('refreshToken')) {
                obj['refreshToken'] = ApiClient.convertToType(data['refreshToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} refreshToken
 */
RefreshTokenRequest.prototype['refreshToken'] = undefined;






export default RefreshTokenRequest;

