/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SignRequest model module.
 * @module model/SignRequest
 * @version 1.0.4
 */
class SignRequest {
    /**
     * Constructs a new <code>SignRequest</code>.
     * @alias module:model/SignRequest
     * @param name {String} 
     */
    constructor(name) { 
        
        SignRequest.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>SignRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignRequest} obj Optional instance to populate.
     * @return {module:model/SignRequest} The populated <code>SignRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('formData')) {
                obj['formData'] = ApiClient.convertToType(data['formData'], {'String': 'String'});
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
SignRequest.prototype['name'] = undefined;

/**
 * @member {String} method
 */
SignRequest.prototype['method'] = undefined;

/**
 * @member {String} url
 */
SignRequest.prototype['url'] = undefined;

/**
 * @member {Object.<String, String>} formData
 */
SignRequest.prototype['formData'] = undefined;

/**
 * @member {String} path
 */
SignRequest.prototype['path'] = undefined;






export default SignRequest;

