/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserAutocomplete model module.
 * @module model/UserAutocomplete
 * @version 1.0.4
 */
class UserAutocomplete {
    /**
     * Constructs a new <code>UserAutocomplete</code>.
     * User(id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined)
     * @alias module:model/UserAutocomplete
     * @param username {String} Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    constructor(username) { 
        
        UserAutocomplete.initialize(this, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username) { 
        obj['username'] = username;
    }

    /**
     * Constructs a <code>UserAutocomplete</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserAutocomplete} obj Optional instance to populate.
     * @return {module:model/UserAutocomplete} The populated <code>UserAutocomplete</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserAutocomplete();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
 * @member {String} username
 */
UserAutocomplete.prototype['username'] = undefined;

/**
 * @member {Number} id
 */
UserAutocomplete.prototype['id'] = undefined;






export default UserAutocomplete;

