/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/UserRef'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/UserRef'));
  } else {
    // Browser globals (root is window)
    if (!root.SmallEod) {
      root.SmallEod = {};
    }
    root.SmallEod.NotifiedUserApi = factory(root.SmallEod.ApiClient, root.SmallEod.Error, root.SmallEod.UserRef);
  }
}(this, function(ApiClient, Error, UserRef) {
  'use strict';

  /**
   * NotifiedUser service.
   * @module small_eod/NotifiedUserApi
   * @version 1.0.0
   */

  /**
   * Constructs a new NotifiedUserApi. 
   * @alias module:small_eod/NotifiedUserApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Create a notified user reference of case
     * @param {Number} caseId The id of the case to modify
     * @param {module:model/UserRef} userRef New notified user
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserRef} and HTTP response
     */
    this.createNotifiedUserWithHttpInfo = function(caseId, userRef) {
      var postBody = userRef;
      // verify the required parameter 'caseId' is set
      if (caseId === undefined || caseId === null) {
        throw new Error("Missing the required parameter 'caseId' when calling createNotifiedUser");
      }
      // verify the required parameter 'userRef' is set
      if (userRef === undefined || userRef === null) {
        throw new Error("Missing the required parameter 'userRef' when calling createNotifiedUser");
      }

      var pathParams = {
        'caseId': caseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['sessionAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = UserRef;
      return this.apiClient.callApi(
        '/case/{caseId}/notifiedUser', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a notified user reference of case
     * @param {Number} caseId The id of the case to modify
     * @param {module:model/UserRef} userRef New notified user
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserRef}
     */
    this.createNotifiedUser = function(caseId, userRef) {
      return this.createNotifiedUserWithHttpInfo(caseId, userRef)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Deletes a single notified user based on the ID supplied
     * @param {Number} caseId The id of the case to modify
     * @param {Number} notifiedUserId The id of the responsible user to delete
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.deleteNotifiedUserWithHttpInfo = function(caseId, notifiedUserId) {
      var postBody = null;
      // verify the required parameter 'caseId' is set
      if (caseId === undefined || caseId === null) {
        throw new Error("Missing the required parameter 'caseId' when calling deleteNotifiedUser");
      }
      // verify the required parameter 'notifiedUserId' is set
      if (notifiedUserId === undefined || notifiedUserId === null) {
        throw new Error("Missing the required parameter 'notifiedUserId' when calling deleteNotifiedUser");
      }

      var pathParams = {
        'caseId': caseId,
        'notifiedUserId': notifiedUserId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['sessionAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;
      return this.apiClient.callApi(
        '/case/{caseId}/notifiedUser/{notifiedUserId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Deletes a single notified user based on the ID supplied
     * @param {Number} caseId The id of the case to modify
     * @param {Number} notifiedUserId The id of the responsible user to delete
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.deleteNotifiedUser = function(caseId, notifiedUserId) {
      return this.deleteNotifiedUserWithHttpInfo(caseId, notifiedUserId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Info for a specific notified user of case
     * @param {Number} caseId The id of the case to modify
     * @param {Number} notifiedUserId The id of the responsible user to retrieve
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserRef} and HTTP response
     */
    this.shownotifiedUserByIdWithHttpInfo = function(caseId, notifiedUserId) {
      var postBody = null;
      // verify the required parameter 'caseId' is set
      if (caseId === undefined || caseId === null) {
        throw new Error("Missing the required parameter 'caseId' when calling shownotifiedUserById");
      }
      // verify the required parameter 'notifiedUserId' is set
      if (notifiedUserId === undefined || notifiedUserId === null) {
        throw new Error("Missing the required parameter 'notifiedUserId' when calling shownotifiedUserById");
      }

      var pathParams = {
        'caseId': caseId,
        'notifiedUserId': notifiedUserId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['sessionAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = UserRef;
      return this.apiClient.callApi(
        '/case/{caseId}/notifiedUser/{notifiedUserId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Info for a specific notified user of case
     * @param {Number} caseId The id of the case to modify
     * @param {Number} notifiedUserId The id of the responsible user to retrieve
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserRef}
     */
    this.shownotifiedUserById = function(caseId, notifiedUserId) {
      return this.shownotifiedUserByIdWithHttpInfo(caseId, notifiedUserId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
