/**
 * Small_EOD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.dobrawy@siecobywatelska.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmallEod);
  }
}(this, function(expect, SmallEod) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmallEod.AddressData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AddressData', function() {
    it('should create an instance of AddressData', function() {
      // uncomment below and update the code to test AddressData
      //var instance = new SmallEod.AddressData();
      //expect(instance).to.be.a(SmallEod.AddressData);
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new SmallEod.AddressData();
      //expect(instance).to.be();
    });

    it('should have the property epuap (base name: "epuap")', function() {
      // uncomment below and update the code to test the property epuap
      //var instance = new SmallEod.AddressData();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "street")', function() {
      // uncomment below and update the code to test the property street
      //var instance = new SmallEod.AddressData();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postal_code")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instance = new SmallEod.AddressData();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new SmallEod.AddressData();
      //expect(instance).to.be();
    });

    it('should have the property voivodeship (base name: "voivodeship")', function() {
      // uncomment below and update the code to test the property voivodeship
      //var instance = new SmallEod.AddressData();
      //expect(instance).to.be();
    });

    it('should have the property houseNo (base name: "house_no")', function() {
      // uncomment below and update the code to test the property houseNo
      //var instance = new SmallEod.AddressData();
      //expect(instance).to.be();
    });

    it('should have the property flatNo (base name: "flat_no")', function() {
      // uncomment below and update the code to test the property flatNo
      //var instance = new SmallEod.AddressData();
      //expect(instance).to.be();
    });

  });

}));
